import type { FieldDef } from "@canvas/core";

/**
 * Field names of every DBC the server loads, from the structs in
 * `src/server/shared/DataStores/DBCStructure.h` (code research 1.2). The
 * server copies each stored field (format characters n, i, f, s, b) into the
 * next struct member in order and skips x, X and d, so the members, read in
 * order, name the stored positions. Alex decided the naming (PROF-3,
 * 2026-10-07):
 * - arrays are named as the C++ does, counting from 0: `Reagent[0]`; a
 *   96-bit family mask is three words, `SpellFamilyFlags[2]`;
 * - a localized string (16 slots, then the flags) is one field at its first
 *   slot, named after the member: `SpellName`;
 * - an `int32` member on an `i` field is `signed`;
 * - Achievement_Criteria.dbc's union, whose positions mean different things
 *   per criteria type, stays unnamed.
 *
 * Generated from the source at the profile's core commit, not typed by
 * hand; the local-only test derives every entry again and compares.
 */

/** The named positions of one DBC file, and the struct they come from. */
export interface DbcFieldNames {
  readonly file: string;
  readonly struct: string;
  readonly source: readonly string[];
  readonly fields: readonly FieldDef[];
}

export const dbcFieldNames: readonly DbcFieldNames[] = [
  {
    file: "AreaTable.dbc",
    struct: "AreaTableEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:520-530"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "mapid" },
      { index: 2, name: "zone" },
      { index: 3, name: "exploreFlag" },
      { index: 4, name: "flags" },
      { index: 10, name: "area_level", signed: true },
      { index: 11, name: "area_name" },
      { index: 28, name: "team" },
      { index: 29, name: "LiquidTypeOverride[0]" },
      { index: 30, name: "LiquidTypeOverride[1]" },
      { index: 31, name: "LiquidTypeOverride[2]" },
      { index: 32, name: "LiquidTypeOverride[3]" },
    ],
  },
  {
    file: "Achievement.dbc",
    struct: "AchievementEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:41-57"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "requiredFaction", signed: true },
      { index: 2, name: "mapID", signed: true },
      { index: 4, name: "name" },
      { index: 38, name: "categoryId" },
      { index: 39, name: "points" },
      { index: 41, name: "flags" },
      { index: 60, name: "count" },
      { index: 61, name: "refAchievement" },
    ],
  },
  {
    file: "Achievement_Category.dbc",
    struct: "AchievementCategoryEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:62-63"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "parentCategory", signed: true },
    ],
  },
  {
    file: "Achievement_Criteria.dbc",
    struct: "AchievementCriteriaEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:71-514"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "referredAchievement" },
      { index: 2, name: "requiredType" },
      {
        index: 5,
        name: "additionalRequirements[0].additionalRequirement_type",
      },
      {
        index: 6,
        name: "additionalRequirements[0].additionalRequirement_value",
      },
      {
        index: 7,
        name: "additionalRequirements[1].additionalRequirement_type",
      },
      {
        index: 8,
        name: "additionalRequirements[1].additionalRequirement_value",
      },
      { index: 26, name: "flags" },
      { index: 27, name: "timedType" },
      { index: 28, name: "timerStartEvent" },
      { index: 29, name: "timeLimit" },
    ],
  },
  {
    file: "AreaGroup.dbc",
    struct: "AreaGroupEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:550-552"],
    fields: [
      { index: 0, name: "AreaGroupId" },
      { index: 1, name: "AreaId[0]" },
      { index: 2, name: "AreaId[1]" },
      { index: 3, name: "AreaId[2]" },
      { index: 4, name: "AreaId[3]" },
      { index: 5, name: "AreaId[4]" },
      { index: 6, name: "AreaId[5]" },
      { index: 7, name: "nextGroup" },
    ],
  },
  {
    file: "AreaPOI.dbc",
    struct: "AreaPOIEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:557-569"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "icon[0]" },
      { index: 2, name: "icon[1]" },
      { index: 3, name: "icon[2]" },
      { index: 4, name: "icon[3]" },
      { index: 5, name: "icon[4]" },
      { index: 6, name: "icon[5]" },
      { index: 7, name: "icon[6]" },
      { index: 8, name: "icon[7]" },
      { index: 9, name: "icon[8]" },
      { index: 10, name: "icon[9]" },
      { index: 11, name: "icon[10]" },
      { index: 12, name: "x" },
      { index: 13, name: "y" },
      { index: 14, name: "z" },
      { index: 15, name: "mapId" },
      { index: 17, name: "zoneId" },
      { index: 52, name: "worldState" },
    ],
  },
  {
    file: "AuctionHouse.dbc",
    struct: "AuctionHouseEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:575-578"],
    fields: [
      { index: 0, name: "houseId" },
      { index: 1, name: "faction" },
      { index: 2, name: "depositPercent" },
      { index: 3, name: "cutPercent" },
    ],
  },
  {
    file: "BankBagSlotPrices.dbc",
    struct: "BankBagSlotPricesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:585-586"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "price" },
    ],
  },
  {
    file: "BattlemasterList.dbc",
    struct: "BattlemasterListEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:605-612"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "mapid[0]", signed: true },
      { index: 2, name: "mapid[1]", signed: true },
      { index: 3, name: "mapid[2]", signed: true },
      { index: 4, name: "mapid[3]", signed: true },
      { index: 5, name: "mapid[4]", signed: true },
      { index: 6, name: "mapid[5]", signed: true },
      { index: 7, name: "mapid[6]", signed: true },
      { index: 8, name: "mapid[7]", signed: true },
      { index: 9, name: "type" },
      { index: 11, name: "name" },
      { index: 28, name: "maxGroupSize" },
      { index: 29, name: "HolidayWorldStateId" },
    ],
  },
  {
    file: "BarberShopStyle.dbc",
    struct: "BarberShopStyleEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:591-600"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "type" },
      { index: 37, name: "race" },
      { index: 38, name: "gender" },
      { index: 39, name: "hair_id" },
    ],
  },
  {
    file: "CharStartOutfit.dbc",
    struct: "CharStartOutfitEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:622-626"],
    fields: [
      { index: 1, name: "Race" },
      { index: 2, name: "Class" },
      { index: 3, name: "Gender" },
      { index: 5, name: "ItemId[0]", signed: true },
      { index: 6, name: "ItemId[1]", signed: true },
      { index: 7, name: "ItemId[2]", signed: true },
      { index: 8, name: "ItemId[3]", signed: true },
      { index: 9, name: "ItemId[4]", signed: true },
      { index: 10, name: "ItemId[5]", signed: true },
      { index: 11, name: "ItemId[6]", signed: true },
      { index: 12, name: "ItemId[7]", signed: true },
      { index: 13, name: "ItemId[8]", signed: true },
      { index: 14, name: "ItemId[9]", signed: true },
      { index: 15, name: "ItemId[10]", signed: true },
      { index: 16, name: "ItemId[11]", signed: true },
      { index: 17, name: "ItemId[12]", signed: true },
      { index: 18, name: "ItemId[13]", signed: true },
      { index: 19, name: "ItemId[14]", signed: true },
      { index: 20, name: "ItemId[15]", signed: true },
      { index: 21, name: "ItemId[16]", signed: true },
      { index: 22, name: "ItemId[17]", signed: true },
      { index: 23, name: "ItemId[18]", signed: true },
      { index: 24, name: "ItemId[19]", signed: true },
      { index: 25, name: "ItemId[20]", signed: true },
      { index: 26, name: "ItemId[21]", signed: true },
      { index: 27, name: "ItemId[22]", signed: true },
      { index: 28, name: "ItemId[23]", signed: true },
    ],
  },
  {
    file: "CharTitles.dbc",
    struct: "CharTitlesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:633-639"],
    fields: [
      { index: 0, name: "ID" },
      { index: 2, name: "nameMale" },
      { index: 19, name: "nameFemale" },
      { index: 36, name: "bit_index" },
    ],
  },
  {
    file: "ChatChannels.dbc",
    struct: "ChatChannelsEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:644-646"],
    fields: [
      { index: 0, name: "ChannelID" },
      { index: 1, name: "flags" },
      { index: 3, name: "pattern" },
    ],
  },
  {
    file: "ChrClasses.dbc",
    struct: "ChrClassesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:654-668"],
    fields: [
      { index: 0, name: "ClassID" },
      { index: 2, name: "powerType" },
      { index: 4, name: "name" },
      { index: 56, name: "spellfamily" },
      { index: 58, name: "CinematicSequence" },
      { index: 59, name: "expansion" },
    ],
  },
  {
    file: "ChrRaces.dbc",
    struct: "ChrRacesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:680-698"],
    fields: [
      { index: 0, name: "RaceID" },
      { index: 1, name: "Flags" },
      { index: 2, name: "FactionID" },
      { index: 4, name: "model_m" },
      { index: 5, name: "model_f" },
      { index: 7, name: "TeamID" },
      { index: 12, name: "CinematicSequence" },
      { index: 13, name: "alliance" },
      { index: 14, name: "name" },
      { index: 68, name: "expansion" },
    ],
  },
  {
    file: "CinematicCamera.dbc",
    struct: "CinematicCameraEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:705-709"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Model" },
      { index: 2, name: "SoundID" },
      { index: 3, name: "Origin.X" },
      { index: 4, name: "Origin.Y" },
      { index: 5, name: "Origin.Z" },
      { index: 6, name: "OriginFacing" },
    ],
  },
  {
    file: "CinematicSequences.dbc",
    struct: "CinematicSequencesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:714-716"],
    fields: [
      { index: 0, name: "Id" },
      { index: 2, name: "cinematicCamera" },
    ],
  },
  {
    file: "CreatureDisplayInfo.dbc",
    struct: "CreatureDisplayInfoEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:722-726"],
    fields: [
      { index: 0, name: "Displayid" },
      { index: 1, name: "ModelId" },
      { index: 3, name: "ExtendedDisplayInfoID" },
      { index: 4, name: "scale" },
    ],
  },
  {
    file: "CreatureDisplayInfoExtra.dbc",
    struct: "CreatureDisplayInfoExtraEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:741-741"],
    fields: [{ index: 1, name: "DisplayRaceID" }],
  },
  {
    file: "CreatureFamily.dbc",
    struct: "CreatureFamilyEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:755-764"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "minScale" },
      { index: 2, name: "minScaleLevel" },
      { index: 3, name: "maxScale" },
      { index: 4, name: "maxScaleLevel" },
      { index: 5, name: "skillLine[0]" },
      { index: 6, name: "skillLine[1]" },
      { index: 7, name: "petFoodMask" },
      { index: 8, name: "petTalentType", signed: true },
      { index: 10, name: "Name" },
    ],
  },
  {
    file: "CreatureModelData.dbc",
    struct: "CreatureModelDataEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:776-791"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Flags" },
      { index: 4, name: "Scale" },
      { index: 14, name: "CollisionWidth" },
      { index: 15, name: "CollisionHeight" },
      { index: 16, name: "MountHeight" },
    ],
  },
  {
    file: "CreatureSpellData.dbc",
    struct: "CreatureSpellDataEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:811-812"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "spellId[0]" },
      { index: 2, name: "spellId[1]" },
      { index: 3, name: "spellId[2]" },
      { index: 4, name: "spellId[3]" },
    ],
  },
  {
    file: "CreatureType.dbc",
    struct: "CreatureTypeEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:818-818"],
    fields: [{ index: 0, name: "ID" }],
  },
  {
    file: "CurrencyTypes.dbc",
    struct: "CurrencyTypesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:837-839"],
    fields: [
      { index: 1, name: "ItemId" },
      { index: 3, name: "BitIndex" },
    ],
  },
  {
    file: "DestructibleModelData.dbc",
    struct: "DestructibleModelDataEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:844-859"],
    fields: [
      { index: 0, name: "Id" },
      { index: 3, name: "DamagedDisplayId" },
      { index: 7, name: "DestroyedDisplayId" },
      { index: 11, name: "RebuildingDisplayId" },
      { index: 15, name: "SmokeDisplayId" },
    ],
  },
  {
    file: "DungeonEncounter.dbc",
    struct: "DungeonEncounterEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:867-872"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "mapId" },
      { index: 2, name: "difficulty" },
      { index: 4, name: "encounterIndex" },
      { index: 5, name: "encounterName" },
    ],
  },
  {
    file: "DurabilityCosts.dbc",
    struct: "DurabilityCostsEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:879-880"],
    fields: [
      { index: 0, name: "Itemlvl" },
      { index: 1, name: "multiplier[0]" },
      { index: 2, name: "multiplier[1]" },
      { index: 3, name: "multiplier[2]" },
      { index: 4, name: "multiplier[3]" },
      { index: 5, name: "multiplier[4]" },
      { index: 6, name: "multiplier[5]" },
      { index: 7, name: "multiplier[6]" },
      { index: 8, name: "multiplier[7]" },
      { index: 9, name: "multiplier[8]" },
      { index: 10, name: "multiplier[9]" },
      { index: 11, name: "multiplier[10]" },
      { index: 12, name: "multiplier[11]" },
      { index: 13, name: "multiplier[12]" },
      { index: 14, name: "multiplier[13]" },
      { index: 15, name: "multiplier[14]" },
      { index: 16, name: "multiplier[15]" },
      { index: 17, name: "multiplier[16]" },
      { index: 18, name: "multiplier[17]" },
      { index: 19, name: "multiplier[18]" },
      { index: 20, name: "multiplier[19]" },
      { index: 21, name: "multiplier[20]" },
      { index: 22, name: "multiplier[21]" },
      { index: 23, name: "multiplier[22]" },
      { index: 24, name: "multiplier[23]" },
      { index: 25, name: "multiplier[24]" },
      { index: 26, name: "multiplier[25]" },
      { index: 27, name: "multiplier[26]" },
      { index: 28, name: "multiplier[27]" },
      { index: 29, name: "multiplier[28]" },
    ],
  },
  {
    file: "DurabilityQuality.dbc",
    struct: "DurabilityQualityEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:885-886"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "quality_mod" },
    ],
  },
  {
    file: "Emotes.dbc",
    struct: "EmotesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:891-896"],
    fields: [
      { index: 0, name: "Id" },
      { index: 3, name: "Flags" },
      { index: 4, name: "EmoteType" },
      { index: 5, name: "UnitStandState" },
    ],
  },
  {
    file: "EmotesText.dbc",
    struct: "EmotesTextEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:902-903"],
    fields: [
      { index: 0, name: "Id" },
      { index: 2, name: "textid" },
    ],
  },
  {
    file: "Faction.dbc",
    struct: "FactionEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:908-919"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "reputationListID", signed: true },
      { index: 2, name: "BaseRepRaceMask[0]" },
      { index: 3, name: "BaseRepRaceMask[1]" },
      { index: 4, name: "BaseRepRaceMask[2]" },
      { index: 5, name: "BaseRepRaceMask[3]" },
      { index: 6, name: "BaseRepClassMask[0]" },
      { index: 7, name: "BaseRepClassMask[1]" },
      { index: 8, name: "BaseRepClassMask[2]" },
      { index: 9, name: "BaseRepClassMask[3]" },
      { index: 10, name: "BaseRepValue[0]", signed: true },
      { index: 11, name: "BaseRepValue[1]", signed: true },
      { index: 12, name: "BaseRepValue[2]", signed: true },
      { index: 13, name: "BaseRepValue[3]", signed: true },
      { index: 14, name: "ReputationFlags[0]" },
      { index: 15, name: "ReputationFlags[1]" },
      { index: 16, name: "ReputationFlags[2]" },
      { index: 17, name: "ReputationFlags[3]" },
      { index: 18, name: "team" },
      { index: 19, name: "spilloverRateIn" },
      { index: 20, name: "spilloverRateOut" },
      { index: 21, name: "spilloverMaxRankIn" },
      { index: 23, name: "name" },
    ],
  },
  {
    file: "FactionTemplate.dbc",
    struct: "FactionTemplateEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:940-947"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "faction" },
      { index: 2, name: "factionFlags" },
      { index: 3, name: "ourMask" },
      { index: 4, name: "friendlyMask" },
      { index: 5, name: "hostileMask" },
      { index: 6, name: "enemyFaction[0]" },
      { index: 7, name: "enemyFaction[1]" },
      { index: 8, name: "enemyFaction[2]" },
      { index: 9, name: "enemyFaction[3]" },
      { index: 10, name: "friendFaction[0]" },
      { index: 11, name: "friendFaction[1]" },
      { index: 12, name: "friendFaction[2]" },
      { index: 13, name: "friendFaction[3]" },
    ],
  },
  {
    file: "GameObjectArtKit.dbc",
    struct: "GameObjectArtKitEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:997-997"],
    fields: [{ index: 0, name: "ID" }],
  },
  {
    file: "GameObjectDisplayInfo.dbc",
    struct: "GameObjectDisplayInfoEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1004-1012"],
    fields: [
      { index: 0, name: "Displayid" },
      { index: 1, name: "filename" },
      { index: 12, name: "minX" },
      { index: 13, name: "minY" },
      { index: 14, name: "minZ" },
      { index: 15, name: "maxX" },
      { index: 16, name: "maxY" },
      { index: 17, name: "maxZ" },
    ],
  },
  {
    file: "GemProperties.dbc",
    struct: "GemPropertiesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1018-1020"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "spellitemenchantement" },
      { index: 4, name: "color" },
    ],
  },
  {
    file: "GlyphProperties.dbc",
    struct: "GlyphPropertiesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1025-1027"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "SpellId" },
      { index: 2, name: "TypeFlags" },
    ],
  },
  {
    file: "GlyphSlot.dbc",
    struct: "GlyphSlotEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1033-1035"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "TypeFlags" },
      { index: 2, name: "Order" },
    ],
  },
  {
    file: "gtBarberShopCostBase.dbc",
    struct: "GtBarberShopCostBaseEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1046-1046"],
    fields: [{ index: 1, name: "cost" }],
  },
  {
    file: "gtCombatRatings.dbc",
    struct: "GtCombatRatingsEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1051-1051"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtChanceToMeleeCritBase.dbc",
    struct: "GtChanceToMeleeCritBaseEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1056-1056"],
    fields: [{ index: 1, name: "base" }],
  },
  {
    file: "gtChanceToMeleeCrit.dbc",
    struct: "GtChanceToMeleeCritEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1061-1061"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtChanceToSpellCritBase.dbc",
    struct: "GtChanceToSpellCritBaseEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1066-1066"],
    fields: [{ index: 1, name: "base" }],
  },
  {
    file: "gtChanceToSpellCrit.dbc",
    struct: "GtChanceToSpellCritEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1076-1076"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtNPCManaCostScaler.dbc",
    struct: "GtNPCManaCostScalerEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1071-1071"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtOCTClassCombatRatingScalar.dbc",
    struct: "GtOCTClassCombatRatingScalarEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1081-1081"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtOCTRegenHP.dbc",
    struct: "GtOCTRegenHPEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1086-1086"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtRegenHPPerSpt.dbc",
    struct: "GtRegenHPPerSptEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1096-1096"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "gtRegenMPPerSpt.dbc",
    struct: "GtRegenMPPerSptEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1101-1101"],
    fields: [{ index: 1, name: "ratio" }],
  },
  {
    file: "Holidays.dbc",
    struct: "HolidaysEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1128-1138"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Duration[0]" },
      { index: 2, name: "Duration[1]" },
      { index: 3, name: "Duration[2]" },
      { index: 4, name: "Duration[3]" },
      { index: 5, name: "Duration[4]" },
      { index: 6, name: "Duration[5]" },
      { index: 7, name: "Duration[6]" },
      { index: 8, name: "Duration[7]" },
      { index: 9, name: "Duration[8]" },
      { index: 10, name: "Duration[9]" },
      { index: 11, name: "Date[0]" },
      { index: 12, name: "Date[1]" },
      { index: 13, name: "Date[2]" },
      { index: 14, name: "Date[3]" },
      { index: 15, name: "Date[4]" },
      { index: 16, name: "Date[5]" },
      { index: 17, name: "Date[6]" },
      { index: 18, name: "Date[7]" },
      { index: 19, name: "Date[8]" },
      { index: 20, name: "Date[9]" },
      { index: 21, name: "Date[10]" },
      { index: 22, name: "Date[11]" },
      { index: 23, name: "Date[12]" },
      { index: 24, name: "Date[13]" },
      { index: 25, name: "Date[14]" },
      { index: 26, name: "Date[15]" },
      { index: 27, name: "Date[16]" },
      { index: 28, name: "Date[17]" },
      { index: 29, name: "Date[18]" },
      { index: 30, name: "Date[19]" },
      { index: 31, name: "Date[20]" },
      { index: 32, name: "Date[21]" },
      { index: 33, name: "Date[22]" },
      { index: 34, name: "Date[23]" },
      { index: 35, name: "Date[24]" },
      { index: 36, name: "Date[25]" },
      { index: 37, name: "Region" },
      { index: 38, name: "Looping" },
      { index: 39, name: "CalendarFlags[0]" },
      { index: 40, name: "CalendarFlags[1]" },
      { index: 41, name: "CalendarFlags[2]" },
      { index: 42, name: "CalendarFlags[3]" },
      { index: 43, name: "CalendarFlags[4]" },
      { index: 44, name: "CalendarFlags[5]" },
      { index: 45, name: "CalendarFlags[6]" },
      { index: 46, name: "CalendarFlags[7]" },
      { index: 47, name: "CalendarFlags[8]" },
      { index: 48, name: "CalendarFlags[9]" },
      { index: 51, name: "TextureFilename" },
      { index: 52, name: "Priority" },
      { index: 53, name: "CalendarFilterType", signed: true },
    ],
  },
  {
    file: "Item.dbc",
    struct: "ItemEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1144-1151"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "ClassID" },
      { index: 2, name: "SubclassID" },
      { index: 3, name: "SoundOverrideSubclassID", signed: true },
      { index: 4, name: "Material", signed: true },
      { index: 5, name: "DisplayInfoID" },
      { index: 6, name: "InventoryType" },
      { index: 7, name: "SheatheType" },
    ],
  },
  {
    file: "ItemBagFamily.dbc",
    struct: "ItemBagFamilyEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1156-1156"],
    fields: [{ index: 0, name: "ID" }],
  },
  {
    file: "ItemDisplayInfo.dbc",
    struct: "ItemDisplayInfoEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1163-1166"],
    fields: [
      { index: 0, name: "ID" },
      { index: 5, name: "inventoryIcon" },
    ],
  },
  {
    file: "ItemExtendedCost.dbc",
    struct: "ItemExtendedCostEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1189-1195"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "reqhonorpoints" },
      { index: 2, name: "reqarenapoints" },
      { index: 3, name: "reqarenaslot" },
      { index: 4, name: "reqitem[0]" },
      { index: 5, name: "reqitem[1]" },
      { index: 6, name: "reqitem[2]" },
      { index: 7, name: "reqitem[3]" },
      { index: 8, name: "reqitem[4]" },
      { index: 9, name: "reqitemcount[0]" },
      { index: 10, name: "reqitemcount[1]" },
      { index: 11, name: "reqitemcount[2]" },
      { index: 12, name: "reqitemcount[3]" },
      { index: 13, name: "reqitemcount[4]" },
      { index: 14, name: "reqpersonalarenarating" },
    ],
  },
  {
    file: "ItemLimitCategory.dbc",
    struct: "ItemLimitCategoryEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1200-1204"],
    fields: [
      { index: 0, name: "ID" },
      { index: 18, name: "maxCount" },
      { index: 19, name: "mode" },
    ],
  },
  {
    file: "ItemRandomProperties.dbc",
    struct: "ItemRandomPropertiesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1211-1214"],
    fields: [
      { index: 0, name: "ID" },
      { index: 2, name: "Enchantment[0]" },
      { index: 3, name: "Enchantment[1]" },
      { index: 4, name: "Enchantment[2]" },
      { index: 5, name: "Enchantment[3]" },
      { index: 6, name: "Enchantment[4]" },
      { index: 7, name: "Name" },
    ],
  },
  {
    file: "ItemRandomSuffix.dbc",
    struct: "ItemRandomSuffixEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1220-1225"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Name" },
      { index: 19, name: "Enchantment[0]" },
      { index: 20, name: "Enchantment[1]" },
      { index: 21, name: "Enchantment[2]" },
      { index: 22, name: "Enchantment[3]" },
      { index: 23, name: "Enchantment[4]" },
      { index: 24, name: "AllocationPct[0]" },
      { index: 25, name: "AllocationPct[1]" },
      { index: 26, name: "AllocationPct[2]" },
      { index: 27, name: "AllocationPct[3]" },
      { index: 28, name: "AllocationPct[4]" },
    ],
  },
  {
    file: "ItemSet.dbc",
    struct: "ItemSetEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1234-1241"],
    fields: [
      { index: 1, name: "name" },
      { index: 18, name: "itemId[0]" },
      { index: 19, name: "itemId[1]" },
      { index: 20, name: "itemId[2]" },
      { index: 21, name: "itemId[3]" },
      { index: 22, name: "itemId[4]" },
      { index: 23, name: "itemId[5]" },
      { index: 24, name: "itemId[6]" },
      { index: 25, name: "itemId[7]" },
      { index: 26, name: "itemId[8]" },
      { index: 27, name: "itemId[9]" },
      { index: 35, name: "spells[0]" },
      { index: 36, name: "spells[1]" },
      { index: 37, name: "spells[2]" },
      { index: 38, name: "spells[3]" },
      { index: 39, name: "spells[4]" },
      { index: 40, name: "spells[5]" },
      { index: 41, name: "spells[6]" },
      { index: 42, name: "spells[7]" },
      { index: 43, name: "items_to_triggerspell[0]" },
      { index: 44, name: "items_to_triggerspell[1]" },
      { index: 45, name: "items_to_triggerspell[2]" },
      { index: 46, name: "items_to_triggerspell[3]" },
      { index: 47, name: "items_to_triggerspell[4]" },
      { index: 48, name: "items_to_triggerspell[5]" },
      { index: 49, name: "items_to_triggerspell[6]" },
      { index: 50, name: "items_to_triggerspell[7]" },
      { index: 51, name: "required_skill_id" },
      { index: 52, name: "required_skill_value" },
    ],
  },
  {
    file: "LFGDungeons.dbc",
    struct: "LFGDungeonEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1246-1262"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Name" },
      { index: 18, name: "MinLevel" },
      { index: 19, name: "MaxLevel" },
      { index: 20, name: "TargetLevel" },
      { index: 21, name: "TargetLevelMin" },
      { index: 22, name: "TargetLevelMax" },
      { index: 23, name: "MapID" },
      { index: 24, name: "Difficulty" },
      { index: 25, name: "Flags" },
      { index: 26, name: "TypeID" },
      { index: 29, name: "ExpansionLevel" },
      { index: 31, name: "GroupID" },
    ],
  },
  {
    file: "Light.dbc",
    struct: "LightEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1272-1276"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "MapId" },
      { index: 2, name: "X" },
      { index: 3, name: "Y" },
      { index: 4, name: "Z" },
    ],
  },
  {
    file: "LiquidType.dbc",
    struct: "LiquidTypeEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1284-1289"],
    fields: [
      { index: 0, name: "Id" },
      { index: 3, name: "Type" },
      { index: 5, name: "SpellId" },
    ],
  },
  {
    file: "Lock.dbc",
    struct: "LockEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1309-1312"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Type[0]" },
      { index: 2, name: "Type[1]" },
      { index: 3, name: "Type[2]" },
      { index: 4, name: "Type[3]" },
      { index: 5, name: "Type[4]" },
      { index: 6, name: "Type[5]" },
      { index: 7, name: "Type[6]" },
      { index: 8, name: "Type[7]" },
      { index: 9, name: "Index[0]" },
      { index: 10, name: "Index[1]" },
      { index: 11, name: "Index[2]" },
      { index: 12, name: "Index[3]" },
      { index: 13, name: "Index[4]" },
      { index: 14, name: "Index[5]" },
      { index: 15, name: "Index[6]" },
      { index: 16, name: "Index[7]" },
      { index: 17, name: "Skill[0]" },
      { index: 18, name: "Skill[1]" },
      { index: 19, name: "Skill[2]" },
      { index: 20, name: "Skill[3]" },
      { index: 21, name: "Skill[4]" },
      { index: 22, name: "Skill[5]" },
      { index: 23, name: "Skill[6]" },
      { index: 24, name: "Skill[7]" },
    ],
  },
  {
    file: "MailTemplate.dbc",
    struct: "MailTemplateEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1318-1321"],
    fields: [
      { index: 0, name: "ID" },
      { index: 18, name: "content" },
    ],
  },
  {
    file: "Map.dbc",
    struct: "MapEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1326-1346"],
    fields: [
      { index: 0, name: "MapID" },
      { index: 2, name: "map_type" },
      { index: 3, name: "Flags" },
      { index: 5, name: "name" },
      { index: 22, name: "linked_zone" },
      { index: 57, name: "multimap_id" },
      { index: 59, name: "entrance_map", signed: true },
      { index: 60, name: "entrance_x" },
      { index: 61, name: "entrance_y" },
      { index: 63, name: "expansionID" },
      { index: 65, name: "maxPlayers" },
    ],
  },
  {
    file: "MapDifficulty.dbc",
    struct: "MapDifficultyEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1381-1386"],
    fields: [
      { index: 1, name: "MapId" },
      { index: 2, name: "Difficulty" },
      { index: 3, name: "areaTriggerText" },
      { index: 20, name: "resetTime" },
      { index: 21, name: "maxPlayers" },
    ],
  },
  {
    file: "Movie.dbc",
    struct: "MovieEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1392-1392"],
    fields: [{ index: 0, name: "Id" }],
  },
  {
    file: "NamesReserved.dbc",
    struct: "NamesReservedEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1400-1400"],
    fields: [{ index: 1, name: "Pattern" }],
  },
  {
    file: "NamesProfanity.dbc",
    struct: "NamesProfanityEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1407-1407"],
    fields: [{ index: 1, name: "Pattern" }],
  },
  {
    file: "OverrideSpellData.dbc",
    struct: "OverrideSpellDataEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1415-1416"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "spellId[0]" },
      { index: 2, name: "spellId[1]" },
      { index: 3, name: "spellId[2]" },
      { index: 4, name: "spellId[3]" },
      { index: 5, name: "spellId[4]" },
      { index: 6, name: "spellId[5]" },
      { index: 7, name: "spellId[6]" },
      { index: 8, name: "spellId[7]" },
      { index: 9, name: "spellId[8]" },
      { index: 10, name: "spellId[9]" },
    ],
  },
  {
    file: "PowerDisplay.dbc",
    struct: "PowerDisplayEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1422-1423"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "PowerType" },
    ],
  },
  {
    file: "PvpDifficulty.dbc",
    struct: "PvPDifficultyEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1433-1437"],
    fields: [
      { index: 1, name: "mapId" },
      { index: 2, name: "bracketId" },
      { index: 3, name: "minLevel" },
      { index: 4, name: "maxLevel" },
      { index: 5, name: "difficulty" },
    ],
  },
  {
    file: "QuestXP.dbc",
    struct: "QuestXPEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1453-1454"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "Exp[0]" },
      { index: 2, name: "Exp[1]" },
      { index: 3, name: "Exp[2]" },
      { index: 4, name: "Exp[3]" },
      { index: 5, name: "Exp[4]" },
      { index: 6, name: "Exp[5]" },
      { index: 7, name: "Exp[6]" },
      { index: 8, name: "Exp[7]" },
      { index: 9, name: "Exp[8]" },
      { index: 10, name: "Exp[9]" },
    ],
  },
  {
    file: "QuestFactionReward.dbc",
    struct: "QuestFactionRewEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1459-1460"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "QuestRewFactionValue[0]", signed: true },
      { index: 2, name: "QuestRewFactionValue[1]", signed: true },
      { index: 3, name: "QuestRewFactionValue[2]", signed: true },
      { index: 4, name: "QuestRewFactionValue[3]", signed: true },
      { index: 5, name: "QuestRewFactionValue[4]", signed: true },
      { index: 6, name: "QuestRewFactionValue[5]", signed: true },
      { index: 7, name: "QuestRewFactionValue[6]", signed: true },
      { index: 8, name: "QuestRewFactionValue[7]", signed: true },
      { index: 9, name: "QuestRewFactionValue[8]", signed: true },
      { index: 10, name: "QuestRewFactionValue[9]", signed: true },
    ],
  },
  {
    file: "QuestSort.dbc",
    struct: "QuestSortEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1446-1446"],
    fields: [{ index: 0, name: "id" }],
  },
  {
    file: "RandPropPoints.dbc",
    struct: "RandomPropertiesPointsEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1466-1469"],
    fields: [
      { index: 0, name: "itemLevel" },
      { index: 1, name: "EpicPropertiesPoints[0]" },
      { index: 2, name: "EpicPropertiesPoints[1]" },
      { index: 3, name: "EpicPropertiesPoints[2]" },
      { index: 4, name: "EpicPropertiesPoints[3]" },
      { index: 5, name: "EpicPropertiesPoints[4]" },
      { index: 6, name: "RarePropertiesPoints[0]" },
      { index: 7, name: "RarePropertiesPoints[1]" },
      { index: 8, name: "RarePropertiesPoints[2]" },
      { index: 9, name: "RarePropertiesPoints[3]" },
      { index: 10, name: "RarePropertiesPoints[4]" },
      { index: 11, name: "UncommonPropertiesPoints[0]" },
      { index: 12, name: "UncommonPropertiesPoints[1]" },
      { index: 13, name: "UncommonPropertiesPoints[2]" },
      { index: 14, name: "UncommonPropertiesPoints[3]" },
      { index: 15, name: "UncommonPropertiesPoints[4]" },
    ],
  },
  {
    file: "ScalingStatDistribution.dbc",
    struct: "ScalingStatDistributionEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1474-1477"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "StatMod[0]", signed: true },
      { index: 2, name: "StatMod[1]", signed: true },
      { index: 3, name: "StatMod[2]", signed: true },
      { index: 4, name: "StatMod[3]", signed: true },
      { index: 5, name: "StatMod[4]", signed: true },
      { index: 6, name: "StatMod[5]", signed: true },
      { index: 7, name: "StatMod[6]", signed: true },
      { index: 8, name: "StatMod[7]", signed: true },
      { index: 9, name: "StatMod[8]", signed: true },
      { index: 10, name: "StatMod[9]", signed: true },
      { index: 11, name: "Modifier[0]" },
      { index: 12, name: "Modifier[1]" },
      { index: 13, name: "Modifier[2]" },
      { index: 14, name: "Modifier[3]" },
      { index: 15, name: "Modifier[4]" },
      { index: 16, name: "Modifier[5]" },
      { index: 17, name: "Modifier[6]" },
      { index: 18, name: "Modifier[7]" },
      { index: 19, name: "Modifier[8]" },
      { index: 20, name: "Modifier[9]" },
      { index: 21, name: "MaxLevel" },
    ],
  },
  {
    file: "ScalingStatValues.dbc",
    struct: "ScalingStatValuesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1482-1490"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Level" },
      { index: 2, name: "ssdMultiplier[0]" },
      { index: 3, name: "ssdMultiplier[1]" },
      { index: 4, name: "ssdMultiplier[2]" },
      { index: 5, name: "ssdMultiplier[3]" },
      { index: 6, name: "armorMod[0]" },
      { index: 7, name: "armorMod[1]" },
      { index: 8, name: "armorMod[2]" },
      { index: 9, name: "armorMod[3]" },
      { index: 10, name: "dpsMod[0]" },
      { index: 11, name: "dpsMod[1]" },
      { index: 12, name: "dpsMod[2]" },
      { index: 13, name: "dpsMod[3]" },
      { index: 14, name: "dpsMod[4]" },
      { index: 15, name: "dpsMod[5]" },
      { index: 16, name: "spellPower" },
      { index: 17, name: "ssdMultiplier2" },
      { index: 18, name: "ssdMultiplier3" },
      { index: 19, name: "armorMod2[0]" },
      { index: 20, name: "armorMod2[1]" },
      { index: 21, name: "armorMod2[2]" },
      { index: 22, name: "armorMod2[3]" },
      { index: 23, name: "armorMod2[4]" },
    ],
  },
  {
    file: "SkillLine.dbc",
    struct: "SkillLineEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1584-1594"],
    fields: [
      { index: 0, name: "id" },
      { index: 1, name: "categoryId", signed: true },
      { index: 3, name: "name" },
      { index: 37, name: "spellIcon" },
      { index: 55, name: "canLink" },
    ],
  },
  {
    file: "SkillLineAbility.dbc",
    struct: "SkillLineAbilityEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1599-1610"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "SkillLine" },
      { index: 2, name: "Spell" },
      { index: 3, name: "RaceMask" },
      { index: 4, name: "ClassMask" },
      { index: 7, name: "MinSkillLineRank" },
      { index: 8, name: "SupercededBySpell" },
      { index: 9, name: "AcquireMethod" },
      { index: 10, name: "TrivialSkillLineRankHigh" },
      { index: 11, name: "TrivialSkillLineRankLow" },
    ],
  },
  {
    file: "SkillRaceClassInfo.dbc",
    struct: "SkillRaceClassInfoEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1571-1576"],
    fields: [
      { index: 1, name: "SkillID" },
      { index: 2, name: "RaceMask" },
      { index: 3, name: "ClassMask" },
      { index: 4, name: "Flags" },
      { index: 6, name: "SkillTierID" },
    ],
  },
  {
    file: "SkillTiers.dbc",
    struct: "SkillTiersEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1616-1618"],
    fields: [
      { index: 0, name: "ID" },
      { index: 17, name: "Value[0]" },
      { index: 18, name: "Value[1]" },
      { index: 19, name: "Value[2]" },
      { index: 20, name: "Value[3]" },
      { index: 21, name: "Value[4]" },
      { index: 22, name: "Value[5]" },
      { index: 23, name: "Value[6]" },
      { index: 24, name: "Value[7]" },
      { index: 25, name: "Value[8]" },
      { index: 26, name: "Value[9]" },
      { index: 27, name: "Value[10]" },
      { index: 28, name: "Value[11]" },
      { index: 29, name: "Value[12]" },
      { index: 30, name: "Value[13]" },
      { index: 31, name: "Value[14]" },
      { index: 32, name: "Value[15]" },
    ],
  },
  {
    file: "SoundEntries.dbc",
    struct: "SoundEntriesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1623-1623"],
    fields: [{ index: 0, name: "Id" }],
  },
  {
    file: "Spell.dbc",
    struct: "SpellEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1643-1747"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Category" },
      { index: 2, name: "Dispel" },
      { index: 3, name: "Mechanic" },
      { index: 4, name: "Attributes" },
      { index: 5, name: "AttributesEx" },
      { index: 6, name: "AttributesEx2" },
      { index: 7, name: "AttributesEx3" },
      { index: 8, name: "AttributesEx4" },
      { index: 9, name: "AttributesEx5" },
      { index: 10, name: "AttributesEx6" },
      { index: 11, name: "AttributesEx7" },
      { index: 12, name: "Stances" },
      { index: 14, name: "StancesNot" },
      { index: 16, name: "Targets" },
      { index: 17, name: "TargetCreatureType" },
      { index: 18, name: "RequiresSpellFocus" },
      { index: 19, name: "FacingCasterFlags" },
      { index: 20, name: "CasterAuraState" },
      { index: 21, name: "TargetAuraState" },
      { index: 22, name: "CasterAuraStateNot" },
      { index: 23, name: "TargetAuraStateNot" },
      { index: 24, name: "CasterAuraSpell" },
      { index: 25, name: "TargetAuraSpell" },
      { index: 26, name: "ExcludeCasterAuraSpell" },
      { index: 27, name: "ExcludeTargetAuraSpell" },
      { index: 28, name: "CastingTimeIndex" },
      { index: 29, name: "RecoveryTime" },
      { index: 30, name: "CategoryRecoveryTime" },
      { index: 31, name: "InterruptFlags" },
      { index: 32, name: "AuraInterruptFlags" },
      { index: 33, name: "ChannelInterruptFlags" },
      { index: 34, name: "ProcFlags" },
      { index: 35, name: "ProcChance" },
      { index: 36, name: "ProcCharges" },
      { index: 37, name: "MaxLevel" },
      { index: 38, name: "BaseLevel" },
      { index: 39, name: "SpellLevel" },
      { index: 40, name: "DurationIndex" },
      { index: 41, name: "PowerType" },
      { index: 42, name: "ManaCost" },
      { index: 43, name: "ManaCostPerlevel" },
      { index: 44, name: "ManaPerSecond" },
      { index: 45, name: "ManaPerSecondPerLevel" },
      { index: 46, name: "RangeIndex" },
      { index: 47, name: "Speed" },
      { index: 49, name: "StackAmount" },
      { index: 50, name: "Totem[0]" },
      { index: 51, name: "Totem[1]" },
      { index: 52, name: "Reagent[0]", signed: true },
      { index: 53, name: "Reagent[1]", signed: true },
      { index: 54, name: "Reagent[2]", signed: true },
      { index: 55, name: "Reagent[3]", signed: true },
      { index: 56, name: "Reagent[4]", signed: true },
      { index: 57, name: "Reagent[5]", signed: true },
      { index: 58, name: "Reagent[6]", signed: true },
      { index: 59, name: "Reagent[7]", signed: true },
      { index: 60, name: "ReagentCount[0]" },
      { index: 61, name: "ReagentCount[1]" },
      { index: 62, name: "ReagentCount[2]" },
      { index: 63, name: "ReagentCount[3]" },
      { index: 64, name: "ReagentCount[4]" },
      { index: 65, name: "ReagentCount[5]" },
      { index: 66, name: "ReagentCount[6]" },
      { index: 67, name: "ReagentCount[7]" },
      { index: 68, name: "EquippedItemClass", signed: true },
      { index: 69, name: "EquippedItemSubClassMask", signed: true },
      { index: 70, name: "EquippedItemInventoryTypeMask", signed: true },
      { index: 71, name: "Effect[0]" },
      { index: 72, name: "Effect[1]" },
      { index: 73, name: "Effect[2]" },
      { index: 74, name: "EffectDieSides[0]", signed: true },
      { index: 75, name: "EffectDieSides[1]", signed: true },
      { index: 76, name: "EffectDieSides[2]", signed: true },
      { index: 77, name: "EffectRealPointsPerLevel[0]" },
      { index: 78, name: "EffectRealPointsPerLevel[1]" },
      { index: 79, name: "EffectRealPointsPerLevel[2]" },
      { index: 80, name: "EffectBasePoints[0]", signed: true },
      { index: 81, name: "EffectBasePoints[1]", signed: true },
      { index: 82, name: "EffectBasePoints[2]", signed: true },
      { index: 83, name: "EffectMechanic[0]" },
      { index: 84, name: "EffectMechanic[1]" },
      { index: 85, name: "EffectMechanic[2]" },
      { index: 86, name: "EffectImplicitTargetA[0]" },
      { index: 87, name: "EffectImplicitTargetA[1]" },
      { index: 88, name: "EffectImplicitTargetA[2]" },
      { index: 89, name: "EffectImplicitTargetB[0]" },
      { index: 90, name: "EffectImplicitTargetB[1]" },
      { index: 91, name: "EffectImplicitTargetB[2]" },
      { index: 92, name: "EffectRadiusIndex[0]" },
      { index: 93, name: "EffectRadiusIndex[1]" },
      { index: 94, name: "EffectRadiusIndex[2]" },
      { index: 95, name: "EffectApplyAuraName[0]" },
      { index: 96, name: "EffectApplyAuraName[1]" },
      { index: 97, name: "EffectApplyAuraName[2]" },
      { index: 98, name: "EffectAmplitude[0]" },
      { index: 99, name: "EffectAmplitude[1]" },
      { index: 100, name: "EffectAmplitude[2]" },
      { index: 101, name: "EffectValueMultiplier[0]" },
      { index: 102, name: "EffectValueMultiplier[1]" },
      { index: 103, name: "EffectValueMultiplier[2]" },
      { index: 104, name: "EffectChainTarget[0]" },
      { index: 105, name: "EffectChainTarget[1]" },
      { index: 106, name: "EffectChainTarget[2]" },
      { index: 107, name: "EffectItemType[0]" },
      { index: 108, name: "EffectItemType[1]" },
      { index: 109, name: "EffectItemType[2]" },
      { index: 110, name: "EffectMiscValue[0]", signed: true },
      { index: 111, name: "EffectMiscValue[1]", signed: true },
      { index: 112, name: "EffectMiscValue[2]", signed: true },
      { index: 113, name: "EffectMiscValueB[0]", signed: true },
      { index: 114, name: "EffectMiscValueB[1]", signed: true },
      { index: 115, name: "EffectMiscValueB[2]", signed: true },
      { index: 116, name: "EffectTriggerSpell[0]" },
      { index: 117, name: "EffectTriggerSpell[1]" },
      { index: 118, name: "EffectTriggerSpell[2]" },
      { index: 119, name: "EffectPointsPerComboPoint[0]" },
      { index: 120, name: "EffectPointsPerComboPoint[1]" },
      { index: 121, name: "EffectPointsPerComboPoint[2]" },
      { index: 122, name: "EffectSpellClassMask[0][0]" },
      { index: 123, name: "EffectSpellClassMask[0][1]" },
      { index: 124, name: "EffectSpellClassMask[0][2]" },
      { index: 125, name: "EffectSpellClassMask[1][0]" },
      { index: 126, name: "EffectSpellClassMask[1][1]" },
      { index: 127, name: "EffectSpellClassMask[1][2]" },
      { index: 128, name: "EffectSpellClassMask[2][0]" },
      { index: 129, name: "EffectSpellClassMask[2][1]" },
      { index: 130, name: "EffectSpellClassMask[2][2]" },
      { index: 131, name: "SpellVisual[0]" },
      { index: 132, name: "SpellVisual[1]" },
      { index: 133, name: "SpellIconID" },
      { index: 134, name: "ActiveIconID" },
      { index: 135, name: "SpellPriority" },
      { index: 136, name: "SpellName" },
      { index: 153, name: "Rank" },
      { index: 204, name: "ManaCostPercentage" },
      { index: 205, name: "StartRecoveryCategory" },
      { index: 206, name: "StartRecoveryTime" },
      { index: 207, name: "MaxTargetLevel" },
      { index: 208, name: "SpellFamilyName" },
      { index: 209, name: "SpellFamilyFlags[0]" },
      { index: 210, name: "SpellFamilyFlags[1]" },
      { index: 211, name: "SpellFamilyFlags[2]" },
      { index: 212, name: "MaxAffectedTargets" },
      { index: 213, name: "DmgClass" },
      { index: 214, name: "PreventionType" },
      { index: 216, name: "EffectDamageMultiplier[0]" },
      { index: 217, name: "EffectDamageMultiplier[1]" },
      { index: 218, name: "EffectDamageMultiplier[2]" },
      { index: 222, name: "TotemCategory[0]" },
      { index: 223, name: "TotemCategory[1]" },
      { index: 224, name: "AreaGroupId", signed: true },
      { index: 225, name: "SchoolMask" },
      { index: 226, name: "RuneCostID" },
      { index: 229, name: "EffectBonusMultiplier[0]" },
      { index: 230, name: "EffectBonusMultiplier[1]" },
      { index: 231, name: "EffectBonusMultiplier[2]" },
    ],
  },
  {
    file: "SpellCastTimes.dbc",
    struct: "SpellCastTimesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1759-1760"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "CastTime", signed: true },
    ],
  },
  {
    file: "SpellCategory.dbc",
    struct: "SpellCategoryEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1767-1768"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Flags" },
    ],
  },
  {
    file: "SpellDifficulty.dbc",
    struct: "SpellDifficultyEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1773-1774"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "SpellID[0]", signed: true },
      { index: 2, name: "SpellID[1]", signed: true },
      { index: 3, name: "SpellID[2]", signed: true },
      { index: 4, name: "SpellID[3]", signed: true },
    ],
  },
  {
    file: "SpellDuration.dbc",
    struct: "SpellDurationEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1834-1835"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Duration[0]", signed: true },
      { index: 2, name: "Duration[1]", signed: true },
      { index: 3, name: "Duration[2]", signed: true },
    ],
  },
  {
    file: "SpellFocusObject.dbc",
    struct: "SpellFocusObjectEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1779-1779"],
    fields: [{ index: 0, name: "ID" }],
  },
  {
    file: "SpellItemEnchantment.dbc",
    struct: "SpellItemEnchantmentEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1842-1856"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "charges" },
      { index: 2, name: "type[0]" },
      { index: 3, name: "type[1]" },
      { index: 4, name: "type[2]" },
      { index: 5, name: "amount[0]" },
      { index: 6, name: "amount[1]" },
      { index: 7, name: "amount[2]" },
      { index: 11, name: "spellid[0]" },
      { index: 12, name: "spellid[1]" },
      { index: 13, name: "spellid[2]" },
      { index: 14, name: "description" },
      { index: 31, name: "aura_id" },
      { index: 32, name: "slot" },
      { index: 33, name: "GemID" },
      { index: 34, name: "EnchantmentCondition" },
      { index: 35, name: "requiredSkill" },
      { index: 36, name: "requiredSkillValue" },
      { index: 37, name: "requiredLevel" },
    ],
  },
  {
    file: "SpellItemEnchantmentCondition.dbc",
    struct: "SpellItemEnchantmentConditionEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1861-1866"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "Color[0]" },
      { index: 2, name: "Color[1]" },
      { index: 3, name: "Color[2]" },
      { index: 4, name: "Color[3]" },
      { index: 5, name: "Color[4]" },
      { index: 11, name: "Comparator[0]" },
      { index: 12, name: "Comparator[1]" },
      { index: 13, name: "Comparator[2]" },
      { index: 14, name: "Comparator[3]" },
      { index: 15, name: "Comparator[4]" },
      { index: 16, name: "CompareColor[0]" },
      { index: 17, name: "CompareColor[1]" },
      { index: 18, name: "CompareColor[2]" },
      { index: 19, name: "CompareColor[3]" },
      { index: 20, name: "CompareColor[4]" },
      { index: 21, name: "Value[0]" },
      { index: 22, name: "Value[1]" },
      { index: 23, name: "Value[2]" },
      { index: 24, name: "Value[3]" },
      { index: 25, name: "Value[4]" },
    ],
  },
  {
    file: "SpellRadius.dbc",
    struct: "SpellRadiusEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1786-1789"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "RadiusMin" },
      { index: 2, name: "RadiusPerLevel" },
      { index: 3, name: "RadiusMax" },
    ],
  },
  {
    file: "SpellRange.dbc",
    struct: "SpellRangeEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1794-1797"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "RangeMin[0]" },
      { index: 2, name: "RangeMin[1]" },
      { index: 3, name: "RangeMax[0]" },
      { index: 4, name: "RangeMax[1]" },
      { index: 5, name: "Flags" },
    ],
  },
  {
    file: "SpellRuneCost.dbc",
    struct: "SpellRuneCostEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1806-1808"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "RuneCost[0]" },
      { index: 2, name: "RuneCost[1]" },
      { index: 3, name: "RuneCost[2]" },
      { index: 4, name: "runePowerGain" },
    ],
  },
  {
    file: "SpellShapeshiftForm.dbc",
    struct: "SpellShapeshiftFormEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1818-1829"],
    fields: [
      { index: 0, name: "ID" },
      { index: 19, name: "flags1" },
      { index: 20, name: "creatureType", signed: true },
      { index: 22, name: "attackSpeed" },
      { index: 23, name: "modelID_A" },
      { index: 24, name: "modelID_H" },
      { index: 27, name: "stanceSpell[0]" },
      { index: 28, name: "stanceSpell[1]" },
      { index: 29, name: "stanceSpell[2]" },
      { index: 30, name: "stanceSpell[3]" },
      { index: 31, name: "stanceSpell[4]" },
      { index: 32, name: "stanceSpell[5]" },
      { index: 33, name: "stanceSpell[6]" },
      { index: 34, name: "stanceSpell[7]" },
    ],
  },
  {
    file: "SpellVisual.dbc",
    struct: "SpellVisualEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1879-1880"],
    fields: [
      { index: 7, name: "HasMissile" },
      { index: 8, name: "MissileModel", signed: true },
    ],
  },
  {
    file: "StableSlotPrices.dbc",
    struct: "StableSlotPricesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1904-1905"],
    fields: [
      { index: 0, name: "Slot" },
      { index: 1, name: "Price" },
    ],
  },
  {
    file: "SummonProperties.dbc",
    struct: "SummonPropertiesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1910-1915"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "Category" },
      { index: 2, name: "Faction" },
      { index: 3, name: "Type" },
      { index: 4, name: "Slot" },
      { index: 5, name: "Flags" },
    ],
  },
  {
    file: "Talent.dbc",
    struct: "TalentEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1924-1934"],
    fields: [
      { index: 0, name: "TalentID" },
      { index: 1, name: "TalentTab" },
      { index: 2, name: "Row" },
      { index: 3, name: "Col" },
      { index: 4, name: "RankID[0]" },
      { index: 5, name: "RankID[1]" },
      { index: 6, name: "RankID[2]" },
      { index: 7, name: "RankID[3]" },
      { index: 8, name: "RankID[4]" },
      { index: 13, name: "DependsOn" },
      { index: 16, name: "DependsOnRank" },
      { index: 19, name: "addToSpellBook" },
    ],
  },
  {
    file: "TalentTab.dbc",
    struct: "TalentTabEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1941-1948"],
    fields: [
      { index: 0, name: "TalentTabID" },
      { index: 20, name: "ClassMask" },
      { index: 21, name: "petTalentMask" },
      { index: 22, name: "tabpage" },
    ],
  },
  {
    file: "TaxiNodes.dbc",
    struct: "TaxiNodesEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1954-1961"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "map_id" },
      { index: 2, name: "x" },
      { index: 3, name: "y" },
      { index: 4, name: "z" },
      { index: 5, name: "name" },
      { index: 22, name: "MountCreatureID[0]" },
      { index: 23, name: "MountCreatureID[1]" },
    ],
  },
  {
    file: "TaxiPath.dbc",
    struct: "TaxiPathEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1966-1969"],
    fields: [
      { index: 0, name: "ID" },
      { index: 1, name: "from" },
      { index: 2, name: "to" },
      { index: 3, name: "price" },
    ],
  },
  {
    file: "TaxiPathNode.dbc",
    struct: "TaxiPathNodeEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1975-1984"],
    fields: [
      { index: 1, name: "path" },
      { index: 2, name: "index" },
      { index: 3, name: "mapid" },
      { index: 4, name: "x" },
      { index: 5, name: "y" },
      { index: 6, name: "z" },
      { index: 7, name: "actionFlag" },
      { index: 8, name: "delay" },
      { index: 9, name: "arrivalEventID" },
      { index: 10, name: "departureEventID" },
    ],
  },
  {
    file: "TeamContributionPoints.dbc",
    struct: "TeamContributionPointsEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1990-1990"],
    fields: [{ index: 1, name: "value" }],
  },
  {
    file: "TotemCategory.dbc",
    struct: "TotemCategoryEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1995-1999"],
    fields: [
      { index: 0, name: "ID" },
      { index: 18, name: "categoryType" },
      { index: 19, name: "categoryMask" },
    ],
  },
  {
    file: "TransportAnimation.dbc",
    struct: "TransportAnimationEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2005-2009"],
    fields: [
      { index: 1, name: "TransportEntry" },
      { index: 2, name: "TimeSeg" },
      { index: 3, name: "X" },
      { index: 4, name: "Y" },
      { index: 5, name: "Z" },
    ],
  },
  {
    file: "TransportRotation.dbc",
    struct: "TransportRotationEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2016-2021"],
    fields: [
      { index: 1, name: "TransportEntry" },
      { index: 2, name: "TimeSeg" },
      { index: 3, name: "X" },
      { index: 4, name: "Y" },
      { index: 5, name: "Z" },
      { index: 6, name: "W" },
    ],
  },
  {
    file: "Vehicle.dbc",
    struct: "VehicleEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2028-2058"],
    fields: [
      { index: 0, name: "m_ID" },
      { index: 1, name: "m_flags" },
      { index: 2, name: "m_turnSpeed" },
      { index: 3, name: "m_pitchSpeed" },
      { index: 4, name: "m_pitchMin" },
      { index: 5, name: "m_pitchMax" },
      { index: 6, name: "m_seatID[0]" },
      { index: 7, name: "m_seatID[1]" },
      { index: 8, name: "m_seatID[2]" },
      { index: 9, name: "m_seatID[3]" },
      { index: 10, name: "m_seatID[4]" },
      { index: 11, name: "m_seatID[5]" },
      { index: 12, name: "m_seatID[6]" },
      { index: 13, name: "m_seatID[7]" },
      { index: 14, name: "m_mouseLookOffsetPitch" },
      { index: 15, name: "m_cameraFadeDistScalarMin" },
      { index: 16, name: "m_cameraFadeDistScalarMax" },
      { index: 17, name: "m_cameraPitchOffset" },
      { index: 18, name: "m_facingLimitRight" },
      { index: 19, name: "m_facingLimitLeft" },
      { index: 20, name: "m_msslTrgtTurnLingering" },
      { index: 21, name: "m_msslTrgtPitchLingering" },
      { index: 22, name: "m_msslTrgtMouseLingering" },
      { index: 23, name: "m_msslTrgtEndOpacity" },
      { index: 24, name: "m_msslTrgtArcSpeed" },
      { index: 25, name: "m_msslTrgtArcRepeat" },
      { index: 26, name: "m_msslTrgtArcWidth" },
      { index: 27, name: "m_msslTrgtImpactRadius[0]" },
      { index: 28, name: "m_msslTrgtImpactRadius[1]" },
      { index: 29, name: "m_msslTrgtArcTexture" },
      { index: 30, name: "m_msslTrgtImpactTexture" },
      { index: 31, name: "m_msslTrgtImpactModel[0]" },
      { index: 32, name: "m_msslTrgtImpactModel[1]" },
      { index: 33, name: "m_cameraYawOffset" },
      { index: 34, name: "m_uiLocomotionType" },
      { index: 35, name: "m_msslTrgtImpactTexRadius" },
      { index: 36, name: "m_uiSeatIndicatorType" },
      { index: 37, name: "m_powerDisplayId" },
    ],
  },
  {
    file: "VehicleSeat.dbc",
    struct: "VehicleSeatEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2065-2110"],
    fields: [
      { index: 0, name: "m_ID" },
      { index: 1, name: "m_flags" },
      { index: 2, name: "m_attachmentID", signed: true },
      { index: 3, name: "m_attachmentOffsetX" },
      { index: 4, name: "m_attachmentOffsetY" },
      { index: 5, name: "m_attachmentOffsetZ" },
      { index: 6, name: "m_enterPreDelay" },
      { index: 7, name: "m_enterSpeed" },
      { index: 8, name: "m_enterGravity" },
      { index: 9, name: "m_enterMinDuration" },
      { index: 10, name: "m_enterMaxDuration" },
      { index: 11, name: "m_enterMinArcHeight" },
      { index: 12, name: "m_enterMaxArcHeight" },
      { index: 13, name: "m_enterAnimStart", signed: true },
      { index: 14, name: "m_enterAnimLoop", signed: true },
      { index: 15, name: "m_rideAnimStart", signed: true },
      { index: 16, name: "m_rideAnimLoop", signed: true },
      { index: 17, name: "m_rideUpperAnimStart", signed: true },
      { index: 18, name: "m_rideUpperAnimLoop", signed: true },
      { index: 19, name: "m_exitPreDelay" },
      { index: 20, name: "m_exitSpeed" },
      { index: 21, name: "m_exitGravity" },
      { index: 22, name: "m_exitMinDuration" },
      { index: 23, name: "m_exitMaxDuration" },
      { index: 24, name: "m_exitMinArcHeight" },
      { index: 25, name: "m_exitMaxArcHeight" },
      { index: 26, name: "m_exitAnimStart", signed: true },
      { index: 27, name: "m_exitAnimLoop", signed: true },
      { index: 28, name: "m_exitAnimEnd", signed: true },
      { index: 29, name: "m_passengerYaw" },
      { index: 30, name: "m_passengerPitch" },
      { index: 31, name: "m_passengerRoll" },
      { index: 32, name: "m_passengerAttachmentID", signed: true },
      { index: 33, name: "m_vehicleEnterAnim", signed: true },
      { index: 34, name: "m_vehicleExitAnim", signed: true },
      { index: 35, name: "m_vehicleRideAnimLoop", signed: true },
      { index: 36, name: "m_vehicleEnterAnimBone", signed: true },
      { index: 37, name: "m_vehicleExitAnimBone", signed: true },
      { index: 38, name: "m_vehicleRideAnimLoopBone", signed: true },
      { index: 39, name: "m_vehicleEnterAnimDelay" },
      { index: 40, name: "m_vehicleExitAnimDelay" },
      { index: 41, name: "m_vehicleAbilityDisplay" },
      { index: 42, name: "m_enterUISoundID" },
      { index: 43, name: "m_exitUISoundID" },
      { index: 44, name: "m_uiSkin", signed: true },
      { index: 45, name: "m_flagsB" },
    ],
  },
  {
    file: "WMOAreaTable.dbc",
    struct: "WMOAreaTableEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2132-2142"],
    fields: [
      { index: 0, name: "Id" },
      { index: 1, name: "rootId", signed: true },
      { index: 2, name: "adtId", signed: true },
      { index: 3, name: "groupId", signed: true },
      { index: 9, name: "Flags" },
      { index: 10, name: "areaId" },
    ],
  },
  {
    file: "WorldMapArea.dbc",
    struct: "WorldMapAreaEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2150-2157"],
    fields: [
      { index: 1, name: "map_id" },
      { index: 2, name: "area_id" },
      { index: 4, name: "y1" },
      { index: 5, name: "y2" },
      { index: 6, name: "x1" },
      { index: 7, name: "x2" },
      { index: 8, name: "virtual_map_id", signed: true },
    ],
  },
  {
    file: "WorldMapOverlay.dbc",
    struct: "WorldMapOverlayEntry",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:2166-2168"],
    fields: [
      { index: 0, name: "ID" },
      { index: 2, name: "areatableID[0]" },
      { index: 3, name: "areatableID[1]" },
      { index: 4, name: "areatableID[2]" },
      { index: 5, name: "areatableID[3]" },
    ],
  },
];

/**
 * Fields the server skips (`x`) that Canvas still reads, because the code
 * research names them as needed: TalentTab's name, icon and internal name,
 * and SpellRange's two display names (code research 1.2). The struct keeps
 * each one as a commented-out member with its file position, which is where
 * the name and the position come from. `readAs` makes the parser return the
 * words of a skipped string; the icon is a plain number, so it has none.
 */
export const skippedFieldNames: readonly Omit<DbcFieldNames, "struct">[] = [
  {
    file: "TalentTab.dbc",
    source: [
      "core:src/server/shared/DataStores/DBCStructure.h:1942-1944",
      "core:src/server/shared/DataStores/DBCStructure.h:1949",
    ],
    fields: [
      { index: 1, name: "name", readAs: "localized" },
      { index: 18, name: "spellicon" },
      { index: 23, name: "internalname", readAs: "string" },
    ],
  },
  {
    file: "SpellRange.dbc",
    source: ["core:src/server/shared/DataStores/DBCStructure.h:1798-1801"],
    fields: [
      { index: 6, name: "DisplayName", readAs: "localized" },
      { index: 23, name: "DisplayNameShort", readAs: "localized" },
    ],
  },
];
