/**
 * Event numbers to names for each mod-ale `Register*` family, transcribed
 * from `src/LuaEngine/Hooks.h` at the mod-ale commit in `Profile.sources`
 * (code research 3.12). mod-ale does not give Lua scripts these names, so
 * a script passes a bare number and Canvas decodes it here. Numbers missing
 * from a table are gaps the source leaves on purpose (commented `UNUSED`).
 * These are the profile's `hooks` (architecture section 5, `HookTable`).
 *
 * Generated from the source, not typed by hand; the local-only test checks
 * every entry against the file again.
 */

import type { HookTable } from "@canvas/core";

/** One event enum per table: its name, where it is, and its numbered events. */
export const luaHookTables: HookTable[] = [
  {
    id: "PacketEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:95-102"],
    events: [
      { value: 5, name: "PACKET_EVENT_ON_PACKET_RECEIVE" },
      { value: 6, name: "PACKET_EVENT_ON_PACKET_RECEIVE_UNKNOWN" },
      { value: 7, name: "PACKET_EVENT_ON_PACKET_SEND" },
    ],
  },
  {
    id: "ServerEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:104-162"],
    events: [
      { value: 1, name: "SERVER_EVENT_ON_NETWORK_START" },
      { value: 2, name: "SERVER_EVENT_ON_NETWORK_STOP" },
      { value: 3, name: "SERVER_EVENT_ON_SOCKET_OPEN" },
      { value: 4, name: "SERVER_EVENT_ON_SOCKET_CLOSE" },
      { value: 5, name: "SERVER_EVENT_ON_PACKET_RECEIVE" },
      { value: 6, name: "SERVER_EVENT_ON_PACKET_RECEIVE_UNKNOWN" },
      { value: 7, name: "SERVER_EVENT_ON_PACKET_SEND" },
      { value: 8, name: "WORLD_EVENT_ON_OPEN_STATE_CHANGE" },
      { value: 9, name: "WORLD_EVENT_ON_CONFIG_LOAD" },
      { value: 11, name: "WORLD_EVENT_ON_SHUTDOWN_INIT" },
      { value: 12, name: "WORLD_EVENT_ON_SHUTDOWN_CANCEL" },
      { value: 13, name: "WORLD_EVENT_ON_UPDATE" },
      { value: 14, name: "WORLD_EVENT_ON_STARTUP" },
      { value: 15, name: "WORLD_EVENT_ON_SHUTDOWN" },
      { value: 16, name: "ALE_EVENT_ON_LUA_STATE_CLOSE" },
      { value: 17, name: "MAP_EVENT_ON_CREATE" },
      { value: 18, name: "MAP_EVENT_ON_DESTROY" },
      { value: 19, name: "MAP_EVENT_ON_GRID_LOAD" },
      { value: 20, name: "MAP_EVENT_ON_GRID_UNLOAD" },
      { value: 21, name: "MAP_EVENT_ON_PLAYER_ENTER" },
      { value: 22, name: "MAP_EVENT_ON_PLAYER_LEAVE" },
      { value: 23, name: "MAP_EVENT_ON_UPDATE" },
      { value: 24, name: "TRIGGER_EVENT_ON_TRIGGER" },
      { value: 25, name: "WEATHER_EVENT_ON_CHANGE" },
      { value: 26, name: "AUCTION_EVENT_ON_ADD" },
      { value: 27, name: "AUCTION_EVENT_ON_REMOVE" },
      { value: 28, name: "AUCTION_EVENT_ON_SUCCESSFUL" },
      { value: 29, name: "AUCTION_EVENT_ON_EXPIRE" },
      { value: 30, name: "ADDON_EVENT_ON_MESSAGE" },
      { value: 31, name: "WORLD_EVENT_ON_DELETE_CREATURE" },
      { value: 32, name: "WORLD_EVENT_ON_DELETE_GAMEOBJECT" },
      { value: 33, name: "ALE_EVENT_ON_LUA_STATE_OPEN" },
      { value: 34, name: "GAME_EVENT_START" },
      { value: 35, name: "GAME_EVENT_STOP" },
    ],
  },
  {
    id: "PlayerEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:164-243"],
    events: [
      { value: 1, name: "PLAYER_EVENT_ON_CHARACTER_CREATE" },
      { value: 2, name: "PLAYER_EVENT_ON_CHARACTER_DELETE" },
      { value: 3, name: "PLAYER_EVENT_ON_LOGIN" },
      { value: 4, name: "PLAYER_EVENT_ON_LOGOUT" },
      { value: 5, name: "PLAYER_EVENT_ON_SPELL_CAST" },
      { value: 6, name: "PLAYER_EVENT_ON_KILL_PLAYER" },
      { value: 7, name: "PLAYER_EVENT_ON_KILL_CREATURE" },
      { value: 8, name: "PLAYER_EVENT_ON_KILLED_BY_CREATURE" },
      { value: 9, name: "PLAYER_EVENT_ON_DUEL_REQUEST" },
      { value: 10, name: "PLAYER_EVENT_ON_DUEL_START" },
      { value: 11, name: "PLAYER_EVENT_ON_DUEL_END" },
      { value: 12, name: "PLAYER_EVENT_ON_GIVE_XP" },
      { value: 13, name: "PLAYER_EVENT_ON_LEVEL_CHANGE" },
      { value: 14, name: "PLAYER_EVENT_ON_MONEY_CHANGE" },
      { value: 15, name: "PLAYER_EVENT_ON_REPUTATION_CHANGE" },
      { value: 16, name: "PLAYER_EVENT_ON_TALENTS_CHANGE" },
      { value: 17, name: "PLAYER_EVENT_ON_TALENTS_RESET" },
      { value: 18, name: "PLAYER_EVENT_ON_CHAT" },
      { value: 19, name: "PLAYER_EVENT_ON_WHISPER" },
      { value: 20, name: "PLAYER_EVENT_ON_GROUP_CHAT" },
      { value: 21, name: "PLAYER_EVENT_ON_GUILD_CHAT" },
      { value: 22, name: "PLAYER_EVENT_ON_CHANNEL_CHAT" },
      { value: 23, name: "PLAYER_EVENT_ON_EMOTE" },
      { value: 24, name: "PLAYER_EVENT_ON_TEXT_EMOTE" },
      { value: 25, name: "PLAYER_EVENT_ON_SAVE" },
      { value: 26, name: "PLAYER_EVENT_ON_BIND_TO_INSTANCE" },
      { value: 27, name: "PLAYER_EVENT_ON_UPDATE_ZONE" },
      { value: 28, name: "PLAYER_EVENT_ON_MAP_CHANGE" },
      { value: 29, name: "PLAYER_EVENT_ON_EQUIP" },
      { value: 30, name: "PLAYER_EVENT_ON_FIRST_LOGIN" },
      { value: 31, name: "PLAYER_EVENT_ON_CAN_USE_ITEM" },
      { value: 32, name: "PLAYER_EVENT_ON_LOOT_ITEM" },
      { value: 33, name: "PLAYER_EVENT_ON_ENTER_COMBAT" },
      { value: 34, name: "PLAYER_EVENT_ON_LEAVE_COMBAT" },
      { value: 35, name: "PLAYER_EVENT_ON_REPOP" },
      { value: 36, name: "PLAYER_EVENT_ON_RESURRECT" },
      { value: 37, name: "PLAYER_EVENT_ON_LOOT_MONEY" },
      { value: 38, name: "PLAYER_EVENT_ON_QUEST_ABANDON" },
      { value: 39, name: "PLAYER_EVENT_ON_LEARN_TALENTS" },
      { value: 42, name: "PLAYER_EVENT_ON_COMMAND" },
      { value: 43, name: "PLAYER_EVENT_ON_PET_ADDED_TO_WORLD" },
      { value: 44, name: "PLAYER_EVENT_ON_LEARN_SPELL" },
      { value: 45, name: "PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE" },
      { value: 46, name: "PLAYER_EVENT_ON_FFAPVP_CHANGE" },
      { value: 47, name: "PLAYER_EVENT_ON_UPDATE_AREA" },
      { value: 48, name: "PLAYER_EVENT_ON_CAN_INIT_TRADE" },
      { value: 49, name: "PLAYER_EVENT_ON_CAN_SEND_MAIL" },
      { value: 50, name: "PLAYER_EVENT_ON_CAN_JOIN_LFG" },
      { value: 51, name: "PLAYER_EVENT_ON_QUEST_REWARD_ITEM" },
      { value: 52, name: "PLAYER_EVENT_ON_CREATE_ITEM" },
      { value: 53, name: "PLAYER_EVENT_ON_STORE_NEW_ITEM" },
      { value: 54, name: "PLAYER_EVENT_ON_COMPLETE_QUEST" },
      { value: 55, name: "PLAYER_EVENT_ON_CAN_GROUP_INVITE" },
      { value: 56, name: "PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM" },
      { value: 57, name: "PLAYER_EVENT_ON_BG_DESERTION" },
      { value: 58, name: "PLAYER_EVENT_ON_PET_KILL" },
      { value: 59, name: "PLAYER_EVENT_ON_CAN_RESURRECT" },
      { value: 60, name: "PLAYER_EVENT_ON_CAN_UPDATE_SKILL" },
      { value: 61, name: "PLAYER_EVENT_ON_BEFORE_UPDATE_SKILL" },
      { value: 62, name: "PLAYER_EVENT_ON_UPDATE_SKILL" },
      { value: 63, name: "PLAYER_EVENT_ON_QUEST_ACCEPT" },
      { value: 64, name: "PLAYER_EVENT_ON_AURA_APPLY" },
      { value: 65, name: "PLAYER_EVENT_ON_HEAL" },
      { value: 66, name: "PLAYER_EVENT_ON_DAMAGE" },
      { value: 67, name: "PLAYER_EVENT_ON_AURA_REMOVE" },
      { value: 68, name: "PLAYER_EVENT_ON_MODIFY_PERIODIC_DAMAGE_AURAS_TICK" },
      { value: 69, name: "PLAYER_EVENT_ON_MODIFY_MELEE_DAMAGE" },
      { value: 70, name: "PLAYER_EVENT_ON_MODIFY_SPELL_DAMAGE_TAKEN" },
      { value: 71, name: "PLAYER_EVENT_ON_MODIFY_HEAL_RECEIVED" },
      { value: 72, name: "PLAYER_EVENT_ON_DEAL_DAMAGE" },
      { value: 73, name: "PLAYER_EVENT_ON_RELEASED_GHOST" },
    ],
  },
  {
    id: "GuildEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:245-261"],
    events: [
      { value: 1, name: "GUILD_EVENT_ON_ADD_MEMBER" },
      { value: 2, name: "GUILD_EVENT_ON_REMOVE_MEMBER" },
      { value: 3, name: "GUILD_EVENT_ON_MOTD_CHANGE" },
      { value: 4, name: "GUILD_EVENT_ON_INFO_CHANGE" },
      { value: 5, name: "GUILD_EVENT_ON_CREATE" },
      { value: 6, name: "GUILD_EVENT_ON_DISBAND" },
      { value: 7, name: "GUILD_EVENT_ON_MONEY_WITHDRAW" },
      { value: 8, name: "GUILD_EVENT_ON_MONEY_DEPOSIT" },
      { value: 9, name: "GUILD_EVENT_ON_ITEM_MOVE" },
      { value: 10, name: "GUILD_EVENT_ON_EVENT" },
      { value: 11, name: "GUILD_EVENT_ON_BANK_EVENT" },
    ],
  },
  {
    id: "GroupEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:263-274"],
    events: [
      { value: 1, name: "GROUP_EVENT_ON_MEMBER_ADD" },
      { value: 2, name: "GROUP_EVENT_ON_MEMBER_INVITE" },
      { value: 3, name: "GROUP_EVENT_ON_MEMBER_REMOVE" },
      { value: 4, name: "GROUP_EVENT_ON_LEADER_CHANGE" },
      { value: 5, name: "GROUP_EVENT_ON_DISBAND" },
      { value: 6, name: "GROUP_EVENT_ON_CREATE" },
    ],
  },
  {
    id: "VehicleEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:276-286"],
    events: [
      { value: 1, name: "VEHICLE_EVENT_ON_INSTALL" },
      { value: 2, name: "VEHICLE_EVENT_ON_UNINSTALL" },
      { value: 4, name: "VEHICLE_EVENT_ON_INSTALL_ACCESSORY" },
      { value: 5, name: "VEHICLE_EVENT_ON_ADD_PASSENGER" },
      { value: 6, name: "VEHICLE_EVENT_ON_REMOVE_PASSENGER" },
    ],
  },
  {
    id: "CreatureEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:288-337"],
    events: [
      { value: 1, name: "CREATURE_EVENT_ON_ENTER_COMBAT" },
      { value: 2, name: "CREATURE_EVENT_ON_LEAVE_COMBAT" },
      { value: 3, name: "CREATURE_EVENT_ON_TARGET_DIED" },
      { value: 4, name: "CREATURE_EVENT_ON_DIED" },
      { value: 5, name: "CREATURE_EVENT_ON_SPAWN" },
      { value: 6, name: "CREATURE_EVENT_ON_REACH_WP" },
      { value: 7, name: "CREATURE_EVENT_ON_AIUPDATE" },
      { value: 8, name: "CREATURE_EVENT_ON_RECEIVE_EMOTE" },
      { value: 9, name: "CREATURE_EVENT_ON_DAMAGE_TAKEN" },
      { value: 10, name: "CREATURE_EVENT_ON_PRE_COMBAT" },
      { value: 12, name: "CREATURE_EVENT_ON_OWNER_ATTACKED" },
      { value: 13, name: "CREATURE_EVENT_ON_OWNER_ATTACKED_AT" },
      { value: 14, name: "CREATURE_EVENT_ON_HIT_BY_SPELL" },
      { value: 15, name: "CREATURE_EVENT_ON_SPELL_HIT_TARGET" },
      { value: 19, name: "CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE" },
      { value: 20, name: "CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN" },
      { value: 21, name: "CREATURE_EVENT_ON_SUMMONED_CREATURE_DIED" },
      { value: 22, name: "CREATURE_EVENT_ON_SUMMONED" },
      { value: 23, name: "CREATURE_EVENT_ON_RESET" },
      { value: 24, name: "CREATURE_EVENT_ON_REACH_HOME" },
      { value: 26, name: "CREATURE_EVENT_ON_CORPSE_REMOVED" },
      { value: 27, name: "CREATURE_EVENT_ON_MOVE_IN_LOS" },
      { value: 30, name: "CREATURE_EVENT_ON_DUMMY_EFFECT" },
      { value: 31, name: "CREATURE_EVENT_ON_QUEST_ACCEPT" },
      { value: 34, name: "CREATURE_EVENT_ON_QUEST_REWARD" },
      { value: 35, name: "CREATURE_EVENT_ON_DIALOG_STATUS" },
      { value: 36, name: "CREATURE_EVENT_ON_ADD" },
      { value: 37, name: "CREATURE_EVENT_ON_REMOVE" },
      { value: 38, name: "CREATURE_EVENT_ON_AURA_APPLY" },
      { value: 39, name: "CREATURE_EVENT_ON_HEAL" },
      { value: 40, name: "CREATURE_EVENT_ON_DAMAGE" },
      { value: 41, name: "CREATURE_EVENT_ON_AURA_REMOVE" },
      {
        value: 42,
        name: "CREATURE_EVENT_ON_MODIFY_PERIODIC_DAMAGE_AURAS_TICK",
      },
      { value: 43, name: "CREATURE_EVENT_ON_MODIFY_MELEE_DAMAGE" },
      { value: 44, name: "CREATURE_EVENT_ON_MODIFY_SPELL_DAMAGE_TAKEN" },
      { value: 45, name: "CREATURE_EVENT_ON_MODIFY_HEAL_RECEIVED" },
      { value: 46, name: "CREATURE_EVENT_ON_DEAL_DAMAGE" },
    ],
  },
  {
    id: "GameObjectEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:339-356"],
    events: [
      { value: 1, name: "GAMEOBJECT_EVENT_ON_AIUPDATE" },
      { value: 2, name: "GAMEOBJECT_EVENT_ON_SPAWN" },
      { value: 3, name: "GAMEOBJECT_EVENT_ON_DUMMY_EFFECT" },
      { value: 4, name: "GAMEOBJECT_EVENT_ON_QUEST_ACCEPT" },
      { value: 5, name: "GAMEOBJECT_EVENT_ON_QUEST_REWARD" },
      { value: 6, name: "GAMEOBJECT_EVENT_ON_DIALOG_STATUS" },
      { value: 7, name: "GAMEOBJECT_EVENT_ON_DESTROYED" },
      { value: 8, name: "GAMEOBJECT_EVENT_ON_DAMAGED" },
      { value: 9, name: "GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE" },
      { value: 10, name: "GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED" },
      { value: 12, name: "GAMEOBJECT_EVENT_ON_ADD" },
      { value: 13, name: "GAMEOBJECT_EVENT_ON_REMOVE" },
      { value: 14, name: "GAMEOBJECT_EVENT_ON_USE" },
    ],
  },
  {
    id: "ItemEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:358-366"],
    events: [
      { value: 1, name: "ITEM_EVENT_ON_DUMMY_EFFECT" },
      { value: 2, name: "ITEM_EVENT_ON_USE" },
      { value: 3, name: "ITEM_EVENT_ON_QUEST_ACCEPT" },
      { value: 4, name: "ITEM_EVENT_ON_EXPIRE" },
      { value: 5, name: "ITEM_EVENT_ON_REMOVE" },
    ],
  },
  {
    id: "GossipEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:368-373"],
    events: [
      { value: 1, name: "GOSSIP_EVENT_ON_HELLO" },
      { value: 2, name: "GOSSIP_EVENT_ON_SELECT" },
    ],
  },
  {
    id: "BGEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:375-382"],
    events: [
      { value: 1, name: "BG_EVENT_ON_START" },
      { value: 2, name: "BG_EVENT_ON_END" },
      { value: 3, name: "BG_EVENT_ON_CREATE" },
      { value: 4, name: "BG_EVENT_ON_PRE_DESTROY" },
    ],
  },
  {
    id: "InstanceEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:384-394"],
    events: [
      { value: 1, name: "INSTANCE_EVENT_ON_INITIALIZE" },
      { value: 2, name: "INSTANCE_EVENT_ON_LOAD" },
      { value: 3, name: "INSTANCE_EVENT_ON_UPDATE" },
      { value: 4, name: "INSTANCE_EVENT_ON_PLAYER_ENTER" },
      { value: 5, name: "INSTANCE_EVENT_ON_CREATURE_CREATE" },
      { value: 6, name: "INSTANCE_EVENT_ON_GAMEOBJECT_CREATE" },
      { value: 7, name: "INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS" },
    ],
  },
  {
    id: "TicketEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:396-403"],
    events: [
      { value: 1, name: "TICKET_EVENT_ON_CREATE" },
      { value: 2, name: "TICKET_EVENT_UPDATE_LAST_CHANGE" },
      { value: 3, name: "TICKET_EVENT_ON_CLOSE" },
      { value: 4, name: "TICKET_EVENT_ON_RESOLVE" },
    ],
  },
  {
    id: "SpellEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:405-411"],
    events: [
      { value: 1, name: "SPELL_EVENT_ON_PREPARE" },
      { value: 2, name: "SPELL_EVENT_ON_CAST" },
      { value: 3, name: "SPELL_EVENT_ON_CAST_CANCEL" },
    ],
  },
  {
    id: "AllCreatureEvents",
    source: ["mod-ale:src/LuaEngine/Hooks.h:413-429"],
    events: [
      { value: 1, name: "ALL_CREATURE_EVENT_ON_ADD" },
      { value: 2, name: "ALL_CREATURE_EVENT_ON_REMOVE" },
      { value: 3, name: "ALL_CREATURE_EVENT_ON_SELECT_LEVEL" },
      { value: 4, name: "ALL_CREATURE_EVENT_ON_BEFORE_SELECT_LEVEL" },
      { value: 5, name: "ALL_CREATURE_EVENT_ON_AURA_APPLY" },
      { value: 6, name: "ALL_CREATURE_EVENT_ON_HEAL" },
      { value: 7, name: "ALL_CREATURE_EVENT_ON_DAMAGE" },
      { value: 8, name: "ALL_CREATURE_EVENT_ON_AURA_REMOVE" },
      {
        value: 9,
        name: "ALL_CREATURE_EVENT_ON_MODIFY_PERIODIC_DAMAGE_AURAS_TICK",
      },
      { value: 10, name: "ALL_CREATURE_EVENT_ON_MODIFY_MELEE_DAMAGE" },
      { value: 11, name: "ALL_CREATURE_EVENT_ON_MODIFY_SPELL_DAMAGE_TAKEN" },
      { value: 12, name: "ALL_CREATURE_EVENT_ON_MODIFY_HEAL_RECEIVED" },
      { value: 13, name: "ALL_CREATURE_EVENT_ON_DEAL_DAMAGE" },
    ],
  },
];
