import type { BindingDef } from "@canvas/core";

/**
 * Per-dungeon registration macros: each is an alias of
 * RegisterCreatureAIWithFactory or RegisterGameObjectAIWithFactory with the
 * dungeon's own factory, e.g. `#define RegisterKarazhanCreatureAI(ai_name)
 * RegisterCreatureAIWithFactory(ai_name, GetKarazhanAI)` (code research
 * 2.6). They take the class whose name becomes the script name, exactly as
 * the macro they wrap does. All 56 in the clean source are listed by name
 * (Alex, 2026-10-07); the C++ extractor also treats any macro defined in
 * that alias form as one, which catches wrappers a server adds.
 *
 * Generated from the `#define` lines at the core commit; the local-only test
 * reads each one back.
 */
const SCRIPTS = "core:src/server/scripts";

export const wrapperMacros: BindingDef[] = (
  [
    [
      "RegisterBlackrockDepthsCreatureAI",
      "Creature",
      "EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.h",
      154,
    ],
    [
      "RegisterBlackrockDepthsGameObjectAI",
      "GameObject",
      "EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.h",
      155,
    ],
    [
      "RegisterBlackrockSpireCreatureAI",
      "Creature",
      "EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h",
      157,
    ],
    [
      "RegisterBlackrockSpireGameObjectAI",
      "GameObject",
      "EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h",
      158,
    ],
    [
      "RegisterBlackwingLairCreatureAI",
      "Creature",
      "EasternKingdoms/BlackrockMountain/BlackwingLair/blackwing_lair.h",
      129,
    ],
    [
      "RegisterBlackwingLairGameObjectAI",
      "GameObject",
      "EasternKingdoms/BlackrockMountain/BlackwingLair/blackwing_lair.h",
      130,
    ],
    [
      "RegisterMoltenCoreCreatureAI",
      "Creature",
      "EasternKingdoms/BlackrockMountain/MoltenCore/molten_core.h",
      130,
    ],
    [
      "RegisterMoltenCoreGameObjectAI",
      "GameObject",
      "EasternKingdoms/BlackrockMountain/MoltenCore/molten_core.h",
      131,
    ],
    [
      "RegisterKarazhanCreatureAI",
      "Creature",
      "EasternKingdoms/Karazhan/karazhan.h",
      223,
    ],
    [
      "RegisterMagistersTerraceCreatureAI",
      "Creature",
      "EasternKingdoms/MagistersTerrace/magisters_terrace.h",
      83,
    ],
    [
      "RegisterScholomanceCreatureAI",
      "Creature",
      "EasternKingdoms/Scholomance/scholomance.h",
      73,
    ],
    [
      "RegisterShadowfangKeepCreatureAI",
      "Creature",
      "EasternKingdoms/ShadowfangKeep/shadowfang_keep.h",
      56,
    ],
    [
      "RegisterStratholmeCreatureAI",
      "Creature",
      "EasternKingdoms/Stratholme/stratholme.h",
      117,
    ],
    [
      "RegisterSunwellPlateauCreatureAI",
      "Creature",
      "EasternKingdoms/SunwellPlateau/sunwell_plateau.h",
      116,
    ],
    [
      "RegisterZulAmanCreatureAI",
      "Creature",
      "EasternKingdoms/ZulAman/zulaman.h",
      112,
    ],
    [
      "RegisterZulGurubCreatureAI",
      "Creature",
      "EasternKingdoms/ZulGurub/zulgurub.h",
      94,
    ],
    [
      "RegisterHyjalAI",
      "Creature",
      "Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h",
      193,
    ],
    [
      "RegisterOldHillsbradCreatureAI",
      "Creature",
      "Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.h",
      100,
    ],
    [
      "RegisterTheBlackMorassCreatureAI",
      "Creature",
      "Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.h",
      127,
    ],
    [
      "RegisterDireMaulCreatureAI",
      "Creature",
      "Kalimdor/DireMaul/dire_maul.h",
      57,
    ],
    [
      "RegisterOnyxiasLairCreatureAI",
      "Creature",
      "Kalimdor/OnyxiasLair/onyxias_lair.h",
      69,
    ],
    [
      "RegisterRuinsOfAhnQirajCreatureAI",
      "Creature",
      "Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.h",
      91,
    ],
    [
      "RegisterTempleOfAhnQirajCreatureAI",
      "Creature",
      "Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h",
      114,
    ],
    [
      "RegisterAzjolNerubCreatureAI",
      "Creature",
      "Northrend/AzjolNerub/AzjolNerub/azjol_nerub.h",
      77,
    ],
    [
      "RegisterAhnKahetCreatureAI",
      "Creature",
      "Northrend/AzjolNerub/ahnkahet/ahnkahet.h",
      86,
    ],
    [
      "RegisterObsidianSanctumCreatureAI",
      "Creature",
      "Northrend/ChamberOfAspects/ObsidianSanctum/obsidian_sanctum.h",
      72,
    ],
    [
      "RegisterForgeOfSoulsCreatureAI",
      "Creature",
      "Northrend/FrozenHalls/ForgeOfSouls/forge_of_souls.h",
      107,
    ],
    [
      "RegisterHallsOfReflectionCreatureAI",
      "Creature",
      "Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.h",
      413,
    ],
    [
      "RegisterGundrakCreatureAI",
      "Creature",
      "Northrend/Gundrak/gundrak.h",
      74,
    ],
    [
      "RegisterIcecrownCitadelCreatureAI",
      "Creature",
      "Northrend/IcecrownCitadel/icecrown_citadel.h",
      616,
    ],
    [
      "RegisterNaxxramasCreatureAI",
      "Creature",
      "Northrend/Naxxramas/naxxramas.h",
      325,
    ],
    [
      "RegisterEoECreatureAI",
      "Creature",
      "Northrend/Nexus/EyeOfEternity/eye_of_eternity.h",
      148,
    ],
    [
      "RegisterNexusCreatureAI",
      "Creature",
      "Northrend/Nexus/Nexus/nexus.h",
      66,
    ],
    [
      "RegisterHallOfLightningCreatureAI",
      "Creature",
      "Northrend/Ulduar/HallsOfLightning/halls_of_lightning.h",
      70,
    ],
    [
      "RegisterUlduarCreatureAI",
      "Creature",
      "Northrend/Ulduar/Ulduar/ulduar.h",
      454,
    ],
    [
      "RegisterUtgardeKeepCreatureAI",
      "Creature",
      "Northrend/UtgardeKeep/UtgardeKeep/utgarde_keep.h",
      90,
    ],
    [
      "RegisterUtgardePinnacleCreatureAI",
      "Creature",
      "Northrend/UtgardeKeep/UtgardePinnacle/utgarde_pinnacle.h",
      86,
    ],
    [
      "RegisterVioletHoldCreatureAI",
      "Creature",
      "Northrend/VioletHold/violet_hold.h",
      339,
    ],
    [
      "RegisterAuchenaiCryptsCreatureAI",
      "Creature",
      "Outland/Auchindoun/AuchenaiCrypts/auchenai_crypts.h",
      41,
    ],
    [
      "RegisterManaTombsCreatureAI",
      "Creature",
      "Outland/Auchindoun/ManaTombs/mana_tombs.h",
      43,
    ],
    [
      "RegisterSethekkHallsCreatureAI",
      "Creature",
      "Outland/Auchindoun/SethekkHalls/sethekk_halls.h",
      63,
    ],
    [
      "RegisterShadowLabyrinthCreatureAI",
      "Creature",
      "Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h",
      56,
    ],
    [
      "RegisterBlackTempleCreatureAI",
      "Creature",
      "Outland/BlackTemple/black_temple.h",
      130,
    ],
    [
      "RegisterSerpentShrineAI",
      "Creature",
      "Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h",
      112,
    ],
    [
      "RegisterTheSlavePensCreatureAI",
      "Creature",
      "Outland/CoilfangReservoir/SlavePens/the_slave_pens.h",
      86,
    ],
    [
      "RegisterSteamvaultCreatureAI",
      "Creature",
      "Outland/CoilfangReservoir/SteamVault/steam_vault.h",
      65,
    ],
    [
      "RegisterUnderbogCreatureAI",
      "Creature",
      "Outland/CoilfangReservoir/underbog/the_underbog.h",
      48,
    ],
    [
      "RegisterGruulsLairAI",
      "Creature",
      "Outland/GruulsLair/gruuls_lair.h",
      58,
    ],
    [
      "RegisterBloodFurnaceCreatureAI",
      "Creature",
      "Outland/HellfireCitadel/BloodFurnace/blood_furnace.h",
      74,
    ],
    [
      "RegisterHellfireRampartsCreatureAI",
      "Creature",
      "Outland/HellfireCitadel/HellfireRamparts/hellfire_ramparts.h",
      54,
    ],
    [
      "RegisterMagtheridonsLairCreatureAI",
      "Creature",
      "Outland/HellfireCitadel/MagtheridonsLair/magtheridons_lair.h",
      72,
    ],
    [
      "RegisterShatteredHallsCreatureAI",
      "Creature",
      "Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h",
      98,
    ],
    ["RegisterTheEyeAI", "Creature", "Outland/TempestKeep/Eye/the_eye.h", 69],
    [
      "RegisterMechanarCreatureAI",
      "Creature",
      "Outland/TempestKeep/Mechanar/mechanar.h",
      72,
    ],
    [
      "RegisterArcatrazCreatureAI",
      "Creature",
      "Outland/TempestKeep/arcatraz/arcatraz.h",
      83,
    ],
    [
      "RegisterTheBotanicaCreatureAI",
      "Creature",
      "Outland/TempestKeep/botanica/the_botanica.h",
      62,
    ],
  ] as const
)
  // [macro, the AI kind its target macro registers, file, line]
  .map(([symbol, , file, line]) => ({
    id: `cpp.macro.${symbol}`,
    language: "cpp",
    form: "macro",
    symbol,
    args: [{ index: 0, holds: "name" }],
    bound: "db",
    stringify: true,
    emits: "script_registration",
    confidence: "by-name",
    source: [`${SCRIPTS}/${file}:${line}`],
  }));
